export const BUTTONS_GOOD_BAD_ICONS = [
    {
      id: '1',
      name: '0',
      avatar: 'user-1.png',
      numVideos: '2',
    },
    {
      id: '2',
      name: '0',
      avatar: 'user-2.png',
      numVideos: '2',
    },
    {
      id: '3',
      name: '0',
      avatar: 'user-3.png',
      numVideos: '2',
    },
    {
      id: '4',
      name: '0',
      avatar: 'user-4.png',
      numVideos: '2',
    },
    {
      id: '5',
      name: '0',
      avatar: 'user-5.png',
      numVideos: '2',
    },
    {
      id: '6',
      name: '0',
      avatar: 'user-6.png',
      numVideos: '2',
    },
    {
      id: '7',
      name: '0',
      avatar: 'user-7.png',
      numVideos: '2',
    },
    {
      id: '8',
      name: '0',
      avatar: 'user-8.png',
      numVideos: '2',
    },
    {
      id: '9',
      name: '0',
      avatar: 'user-9.png',
      numVideos: '2',
    },
    {
      id: '10',
      name: '0',
      avatar: 'user-10.png',
      numVideos: '2',
    },
    {
      id: '11',
      name: '0',
      avatar: 'user-11.png',
      numVideos: '2',
    },
    {
      id: '12',
      name: '0',
      avatar: 'user-12.png',
      numVideos: '2',
    },
    {
      id: '13',
      name: '0',
      avatar: 'user-13.png',
      numVideos: '2',
    },
    {
      id: '14',
      name: '0',
      avatar: 'user-14.png',
      numVideos: '2',
    },
    {
      id: '15',
      name: '0',
      avatar: 'user-15.png',
      numVideos: '2',
    },
    {
      id: '16',
      name: '0',
      avatar: 'user-16.png',
      numVideos: '2',
    },
    {
      id: '17',
      name: '0',
      avatar: 'user-17.png',
      numVideos: '2',
    },
    {
      id: '18',
      name: '0',
      avatar: 'user-18.png',
      numVideos: '2',
    },
    {
      id: '19',
      name: '0',
      avatar: 'user-19.png',
      numVideos: '2',
    },
    {
      id: '20',
      name: '0',
      avatar: 'user-20.png',
      numVideos: '2',
    },
    {
      id: '21',
      name: '0',
      avatar: 'user-21.png',
      numVideos: '2',
    },
  ];